Repository WPTRT/theme-sniffer, pull requests merged in 2019-07, with the labels that each got.

#167 Updated packages to the latest version
  composer.lock
  package-lock.json
  package.json
  webpack.config.js
Labels: Status: Future Release, Type: Enhancement

#142 Feature/js syntax check
  assets/dev/scripts/theme-sniffer.js
  assets/dev/scripts/utils/sniff-js.js
  src/admin-menus/class-sniff-page.php
  src/callback/class-run-sniffer-callback.php
  webpack.config.js
Labels: Status: Future Release

#170 Feature/update standards
  assets/dev/scripts/index.js
  composer.json
  composer.lock
  package-lock.json
  src/callback/class-run-sniffer-callback.php
  views/theme-sniffer-page.php
Labels: Status: Future Release, Type: Enhancement

#174 Fix the screenshot validator issue
  readme.txt
  src/sniffs/screenshot/class-validator.php
  theme-sniffer.php
Labels: Type: Bug
